### ISSUE TITLE
License choice

### ISSUE THREAD

**Issue by xnox** [keybuk/libnih#14]
I'm not sure if it's deliberate or not, but can license be changed to LGPL-2.1+ or GPL-2.0+? Instead of current GPL-2.0-only ?

**Comment by keybuk** [comment]
It's deliberate

On Wednesday, November 26, 2014, Dimitri John Ledkov <
notifications@github.com> wrote:

> I'm not sure if it's deliberate or not, but can license be changed to
> LGPL-2.1+ or GPL-2.0+? Instead of current GPL-2.0-only ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/keybuk/libnih/issues/14.

## 

Have you ever, ever felt like this?
Had strange things happen?  Are you going round the twist?

**Comment by xnox** [comment]
ok =( shame, I'll double check but looks like I will not be able to use it then, for my new side project. Also looking at e.g. lxc source code it's nih-nih-nih things that could have used libnih - logging/file parsing/mainloop etc.

**Comment by keybuk** [comment]
Sure you can, you can license your side project under GPLv2

On Wed, Nov 26, 2014 at 12:06 PM, Dimitri John Ledkov <
notifications@github.com> wrote:

> ok =( shame, I'll double check but looks like I will not be able to use it
> then, for my new side project. Also looking at e.g. lxc source code it's
> nih-nih-nih things that could have used libnih - logging/file
> parsing/mainloop etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/keybuk/libnih/issues/14#issuecomment-64703467.

## 

Have you ever, ever felt like this?
Had strange things happen?  Are you going round the twist?

**Comment by xnox** [comment]
Not really, the set of licenses I wanted to link against include GPLv2 and LGPLv3 (the rest are bsd / public domain stuff). And these two are not compatible, even if my code is (dual-)licensed under GPLv2...

So I'm stuck in rewritting things or trying out different unfamiliar things that are license compatible. Anyway, my problems =)
